version: '3'
services:
  urip:
    build:
      context: .
    image: "zate75/urip"
    container_name: urip
    restart: always
    networks:
      - internal
      - proxy
    labels:
      - traefik.backend=urip
      - traefik.frontend.rule=Host:urip.fyi
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
  internal:
    external: false

