version: '3'
services:
  urip.fyi:
    build:
      context: .
    image: "zate75/urip.fyi"
    container_name: urip.fyi
    restart: always
    networks:
      - internal
      - proxy
    labels:
      - traefik.backend=urip.fyi
      - traefik.frontend.rule=Host:urip.fyi
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
  internal:
    external: false

