version: "3.3"

networks:
  traefik-public:
    external: true
  internal:
    external: false
    
services:
  dev.urip.fyi:
    image: zate75/urip:dev
    container_name: dev.urip.fyi
    restart: on-failure
    entrypoint: ["/app"]
    
    networks:
      - internal
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.backend=dev.urip.fyi
        - traefik.frontend.rule=Host:dev.urip.fyi
        - traefik.docker.network=traefik-public
        - traefik.enable=true
        - traefik.port=3000
        - traefik.tags=traefik-public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
     
